apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::418476779759:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ST48XO3VDCCE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::418476779759:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-11T17:50:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-11T17:50:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1370"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 00046035-8362-4b5b-b095-3181144da016
